### ISSUE TITLE
log4j not found

### ISSUE THREAD

**Issue by aurgiyalgo** [instagram4j/instagram4j#109]
I'm trying to use Instagram4j on a project with maven, but on loading the file (Minecraft plugin) it throws an error like if log4j isn't built with instagram4j

Edit: Solved. I build log4j with the project itself and it works fine.

`
[19:43:22] [Server thread/ERROR]: Error occurred while enabling AnfitriteCore v0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at org.brunocvcunha.instagram4j.Instagram4j.<clinit>(Instagram4j.java:54) ~[?:?]
	at com.Joselu.AnfitriteCore.Main.onEnable(Main.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
	... 13 more`

Someone else have this problem?

**Comment by brunocvcunha** [comment]
Did you use Maven to import the project? Usually, if you use it will manage all the dependencies already.
If you're using Eclipse, for example, you can do `mvn eclipse:eclipse` and import the project in the IDE.
