### ISSUE TITLE
InstagramLikeRequest may result in JsonParseException inside InstagramLikeResult

### ISSUE THREAD

**Issue by dmcmanam** [instagram4j/instagram4j#143]
I'm sending out likes and occasionally the response from a like request throws a JSON parse exception when the response contains "Oops".
The line numbers may be wrong in my stack trace as I may try to debug this and fix tomorrow.

2018-04-06 08:08:41 [Thread-0] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramLikeResult from Oops, an error occurred.

com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Oops': was expecting ('true', 'false' or 'null')
 at [Source: Oops, an error occurred.
; line: 1, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
	at org.brunocvcunha.instagram4j.requests.InstagramLikeRequest.parseResult(InstagramLikeRequest.java:65)
	at org.brunocvcunha.instagram4j.requests.InstagramLikeRequest.parseResult(InstagramLikeRequest.java:1)
	at org.brunocvcunha.instagram4j.requests.InstagramPostRequest.execute(InstagramPostRequest.java:71)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:305)

**Comment by jemand771** [comment]
I think this may be related to the account being banned or something. I get a similar error when trying to login via the library or a legit browser/android device.

Note that I also can't reset my password or re-login. Account seems gone. Looks like instagram is able to flag bots even if they do almost nothing.

**Comment by dmcmanam** [comment]
Today Instagram is having problems and so that response is much more common than usual.  I'm sure as soon as their servers are working normally again that response will start to be rare again.
