### ISSUE TITLE
It failes to create new Uuid

### ISSUE THREAD

**Issue by kheniparth** [instagram4j/instagram4j#172]
Hi, 

When i try to run the library on OSX then it fails to create UUId with below error. When I debugged the code then I found that it fails at below line in InstagramGenericUtil class. Please let me know if you need anything from my side to figure out why something could happen. 

String uuid = (new UUID()).toString();

Error:
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: org/omg/CORBA/portable/IDLEntity
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.brunocvcunha.instagram4j.util.InstagramGenericUtil.generateUuid(InstagramGenericUtil.java:33)
	at org.brunocvcunha.instagram4j.Instagram4j.setup(Instagram4j.java:134)
	at LoginFrame.run(LoginFrame.java:33)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.IDLEntity
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 13 more

Thank you :)

**Comment by 615283** [comment]
I have the same issue @brunocvcunha

**Comment by brunocvcunha** [comment]
JDK10?

**Comment by 615283** [comment]
Yes

**Comment by 615283** [comment]
Should I migrate thugs project back to 8?

**Comment by brunocvcunha** [comment]
Will switch to another UUID generator soon.
