### ISSUE TITLE
UploadAlbumRequest doesnt work for album containing videos and images

### ISSUE THREAD

**Issue by Aulig** [instagram4j/instagram4j#212]
Hey, 
im sending an InstagramUploadAlbumRequest which contains both videos and images. It works great for albums with only images, so Im pretty sure my code is fine. It ends up saying "Uploaded image isn't in the right format". The video is in mp4 format and can be posted on its own perfectly fine. The aspect ratio on both the image and the video is 1:1 so that should also be fine.

Log:

2018-08-24 11:47:54 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramUploadAlbumRequest
URL Upload: https://i.instagram.com/api/v1/upload/photo/
2018-08-24 11:47:56 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadAlbumRequest  - Photo Upload result: 200, {"upload_id": "1535104074885", "xsharing_nonces": {}, "status": "ok"}
2018-08-24 11:47:56 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramConfigureAlbumResult from {"upload_id": "1535104074885", "xsharing_nonces": {}, "status": "ok"}
URL Upload: https://i.instagram.com/api/v1/upload/photo/
2018-08-24 11:48:04 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadAlbumRequest  - Photo Upload result: 200, {"upload_id": "1535104074886", "xsharing_nonces": {}, "status": "ok"}
2018-08-24 11:48:04 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramConfigureAlbumResult from {"upload_id": "1535104074886", "xsharing_nonces": {}, "status": "ok"}
2018-08-24 11:48:04 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramConfigureAlbumRequest
2018-08-24 11:48:06 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramConfigureAlbumResult from {"message": "Uploaded image isn't in the right format", "status": "fail"}
java.lang.IllegalArgumentException: Failed to configure image: Uploaded image isn't in the right format
	at org.brunocvcunha.instagram4j.requests.InstagramUploadAlbumRequest.execute(InstagramUploadAlbumRequest.java:100)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadAlbumRequest.execute(InstagramUploadAlbumRequest.java:48)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at me.aulig.instagram.InstagramManager.postCollection(InstagramManager.java:176)
	at me.aulig.management.Main.main(Main.java:126)
Configure photo result: InstagramConfigureAlbumResult(super=InstagramConfigurePhotoResult(super=StatusResult(status=fail, message=Uploaded image isn't in the right format, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), media=null, upload_id=null), client_sidecar_id=null)

**Comment by jvogit** [comment]
Hello, video is not supported now. In future it will. I will try.
