### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by Hristijan95** [instagram4j/instagram4j#249]
I am getting the following error when trying to login:

`javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:112)
	at org.apache.http.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:580)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:554)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.brunocvcunha.instagram4j.requests.InstagramPostRequest.execute(InstagramPostRequest.java:63)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:191)
	at MainApplication.main(MainApplication.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)`

**Comment by sickobo** [comment]
I'm getting this error, too. On MacOS X 10.13.6 with both OpenJDK 11 and Oracle SE JDK 11
With JDK8 everything works fine.

**Comment by sickobo** [comment]
for java11 the class Instagram4j.java must be fixed. DefaultHttpClient must be changed to CloseableHttpClient

`if (proxy != null) {        	
        	this.client =  HttpClientBuilder.create().setDefaultCookieStore(cookieStore).setProxy(proxy).build();
        } else {
        	this.client =  HttpClientBuilder.create().setDefaultCookieStore(cookieStore).build();
        }`

and 

`public Optional<Cookie> getCsrfCookie() {
        return cookieStore.getCookies().stream().filter(cookie -> cookie.getName().equalsIgnoreCase("csrftoken")).findFirst();
//        return client.getCookieStore().getCookies().stream().filter(cookie -> cookie.getName().equalsIgnoreCase("csrftoken")).findFirst();
    }`

**Comment by erdemsiyam** [comment]
i get this error too. probable cause jdk11, will you update?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
