### ISSUE TITLE
Could not serialize Instagram4j object

### ISSUE THREAD

**Issue by lmkrtchyan** [instagram4j/instagram4j#257]
Getting an error when trying to serialize Instagram4j object:

Exception in thread "main" org.apache.commons.lang3.SerializationException: java.io.NotSerializableException: org.apache.http.impl.client.InternalHttpClient
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:140)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:154)
	at com.onmyown.bot.BotRun.main(BotRun.java:26)
Caused by: java.io.NotSerializableException: org.apache.http.impl.client.InternalHttpClient
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:138)
	... 2 more

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
