### ISSUE TITLE
Simulate fake android device on Linux server for instagram4j login

### ISSUE THREAD

**Issue by Cake4Ice** [instagram4j/instagram4j#265]
Hi together,

I use instagram4j for uver a year now and I'm so happy with it. Bit thanks @brunocvcunha!
Now I saw, that there is a class called [InstagramConstant.java](https://github.com/brunocvcunha/instagram4j/blob/f160d136b3e5c632c04d5cb7ba0fd38d42542a08/src/main/java/org/brunocvcunha/instagram4j/InstagramConstants.java)

But my only problem always was: When I use instagram4j for many friends, Instagram seems to block the login for most of them on my linux server. Even if two factor authentification is deactivated.

So I thought about a possibility to let instagram think, that my linux server (where instagram4j runs) is an android device. That means I need I way to simulate it. Is this what the InstagramConstants.java class is made for? If yes, how can I use it?

Thanks a lot in advance, keep going!

Best regards,
Jonas

**Comment by Cake4Ice** [comment]
Ok, wow, upgraded from 1.6 to 1.8 and saw that the login now simulates an smartphone device, dope! But:
After upgrad from instagram4j 1.6 to instagram4j 1.8 and upgrade from Java JDK8 to Java JDK11 I receive following error after login:

3:57:09 [Timer-0] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramReadMsisdnHeaderRequest
2019-01-21 23:57:09 [Timer-0] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramFetchHeadersRequest
2019-01-21 23:57:12 [Timer-0] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading StatusResult from {"status": "ok"}
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
        at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:113)
        at org.apache.http.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:580)
        at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:574)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:557)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.brunocvcunha.instagram4j.requests.InstagramPostRequest.execute(InstagramPostRequest.java:63)
        at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
        at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:191)
        at de.cake4ice.UserSessions.getSession(UserSessions.java:43)
        ...

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
