### ISSUE TITLE
Error Video post

### ISSUE THREAD

**Issue by isarjanfaza** [instagram4j/instagram4j#268]
Exception in thread "main" java.lang.IllegalArgumentException: Failed to configure image: Transcode error: Video is too long: 94.156911
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:117)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:44)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.configureThumbnail(InstagramUploadVideoRequest.java:152)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:109)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at Main.sendVideoInstgram(Main.java:131)
	at Main.main(Main.java:142)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-05-02T03:18:46.000000Z
  Duration: 00:01:34.16, start: 0.000000, bitrate: 820 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 690 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2018-05-02T03:18:46.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/01/2018.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2018-05-02T03:18:46.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 05/01/2018.

my code
private static void sendVideoInstgram(String pathimage,String TxtMain) throws ClientProtocolException, IOException{
		
	   
	  
	   
	   instagramporn.sendRequest(new InstagramUploadVideoRequest(
		        new File(pathimage),TxtMain));
		
		
	}

	sendVideoInstgram("D:\\test.mp4","test");

**Comment by osmanmmz** [comment]
instagram video duration have to be 1 min or less. your video duration is 1 min 34 sec. if this is correct :  
" Duration: 00:01:34.16 "

**Comment by isarjanfaza** [comment]
thanks , 
Is there any way to split the movie and upload it simultaneously?

**Comment by osmanmmz** [comment]
I am looking for it.I have a similar problem.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
