### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by erdemsiyam** [instagram4j/instagram4j#283]
2019-03-14 14:00:42 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramReadMsisdnHeaderRequest
2019-03-14 14:00:43 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramFetchHeadersRequest
2019-03-14 14:00:44 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading StatusResult from {"status": "ok"}
Exception in thread "main" **javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated**
	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:112)
	at org.apache.http.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:580)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:554)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.brunocvcunha.instagram4j.requests.InstagramPostRequest.execute(InstagramPostRequest.java:63)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:191)

will you help us? thanks.

**Comment by mmabas77** [comment]
I had the same problem >> i used maven 1.9-snapshot  version and the problem disappeared :-)

**Comment by erdemsiyam** [comment]
> I had the same problem >> i used maven 1.9-snapshot version and the problem disappeared :-)

thanks for reply.
so do i using maven, but when i change the version to 1.9-snapshot then throw error there is no 1.9 version, it says last version is 1.8, would you help? thanks.

**Comment by mmabas77** [comment]
I think this is the lastest version 
https://search.maven.org/artifact/org.brunocvcunha.instagram4j/instagram4j/1.10/jar

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
