### ISSUE TITLE
Adding tags of users to posts

### ISSUE THREAD

**Issue by hellasengineering** [instagram4j/instagram4j#293]
I am having issues with the editMedia example from the homepage. 

I want to be able to tag a user, but it looks like you have to edit the caption as well. Not a big deal, I just pass in the exact caption. But that doesn't seem to work either. 

Here is the code:

`public void editMedia(long mediaId, String caption, Long userId, float posX, float posY) {

		try {
			InstagramEditMediaRequest r = new InstagramEditMediaRequest(mediaId, caption);
			UserTags tags = r.new UserTags();
			tags.getTagsToAdd().add(r.new UserTag(userId.toString(), posX, posY));
			r.setUserTags(tags);

			instagram.sendRequest(r);

		} catch (ClientProtocolException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}`

Here is the error:
`
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Oops': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Oops, an error occurred.
"; line: 1, column: 5]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
	at org.brunocvcunha.instagram4j.requests.InstagramEditMediaRequest.parseResult(InstagramEditMediaRequest.java:75)
	at org.brunocvcunha.instagram4j.requests.InstagramEditMediaRequest.parseResult(InstagramEditMediaRequest.java:40)
	at org.brunocvcunha.instagram4j.requests.InstagramPostRequest.execute(InstagramPostRequest.java:71)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at com.hellas.instagram.data.Instagram.editMedia(Instagram.java:213)
	at com.hellas.instagram.data.ThreadInstagramScheduledPoster.run(ThreadInstagramScheduledPoster.java:68)
	at java.lang.Thread.run(Unknown Source)`

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
