### ISSUE TITLE
InstagramFeedResult | InvalidFormatException: Cannot deserialize value of type `long` from String 

### ISSUE THREAD

**Issue by tayfunyasar** [instagram4j/instagram4j#310]
There is a known error with response "InstagramFeedResult"

`Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "2018137120418781546_caption": not a valid Long value
 at [Source: (StringReader); line: 1, column: 41408] (through reference chain: org.brunocvcunha.instagram4j.requests.payload.InstagramFeedResult["items"]->java.util.ArrayList[6]->org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem["caption"]->org.brunocvcunha.instagram4j.requests.payload.InstagramComment["pk"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004) ~[jackson-databind-2.9.8.jar:2.9.8]
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141) ~[instagram4j-1.10.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111) ~[instagram4j-1.10.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramTimelineFeedRequest.parseResult(InstagramTimelineFeedRequest.java:58) ~[instagram4j-1.10.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramTimelineFeedRequest.parseResult(InstagramTimelineFeedRequest.java:29) ~[instagram4j-1.10.jar:na]
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:56) ~[instagram4j-1.10.jar:na]
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:275) ~[instagram4j-1.10.jar:na]
	at org.brunocvcunha.instagram4j.Instagram4j.emulateUserLoggedIn(Instagram4j.java:290) ~[instagram4j-1.10.jar:na]
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:205) ~[instagram4j-1.10.jar:na]
	at com.x.instagram.service.base.InstagramBaseService.login(InstagramBaseService.java:62) ~[classes/:na]
	at com.x.config.security.auth.XAuthenticationProvider.authenticate(XAuthenticationProvider.java:48) ~[classes/:na]
	... 46 common frames omitted
`

**Comment by FrankHeijden** [comment]
Downgrade to version `1.8`

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
