### ISSUE TITLE
unable to login even after adding all the dependencies

### ISSUE THREAD

**Issue by ashu9g** [instagram4j/instagram4j#321]
I am getting this error when ever my activity is loaded for trying to login user
  ```
  --------- beginning of crash
2019-05-19 12:18:02.306 16550-16550/com.instagram.funfollow E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.instagram.funfollow, PID: 16550
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at org.brunocvcunha.instagram4j.Instagram4j.getCsrfCookie(Instagram4j.java:255)
        at org.brunocvcunha.instagram4j.Instagram4j.getOrFetchCsrf(Instagram4j.java:245)
        at org.brunocvcunha.instagram4j.requests.internal.InstagramReadMsisdnHeaderRequest.getPayload(InstagramReadMsisdnHeaderRequest.java:51)
        at org.brunocvcunha.instagram4j.requests.InstagramPostRequest.execute(InstagramPostRequest.java:54)
        at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
        at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:191)
        at com.instagram.funfollowactivity.LoginImageTeal.onCreate(LoginImageTeal.java:55)
        at android.app.Activity.performCreate(Activity.java:6984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1235)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2986)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6784)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
     Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: ex

```
when i run below code
```

 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login_image_teal); 


        try {
            // Login to instagram

            Instagram4j instagram = Instagram4j.builder().username("my.correct.username").password("xxxxx").build();
            instagram.setup();
            instagram.login();
 
            Snackbar.make(parent_view, "Welcome! Login data submitted- "+instagram.getUserId(), Snackbar.LENGTH_SHORT).show();

        } catch (IOException e) {
            e.printStackTrace();
        }
```

**Comment by jemand771** [comment]
This library does not seem to be compatible with Android.
https://github.com/brunocvcunha/instagram4j/issues?q=android

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
