### ISSUE TITLE
Sometimes login ens with exception

### ISSUE THREAD

**Issue by generalbytes** [instagram4j/instagram4j#323]
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "2037937895951710109_caption": not a valid Long value
 at [Source: (StringReader); line: 1, column: 5302] (through reference chain: org.brunocvcunha.instagram4j.requests.payload.InstagramFeedResult["items"]->java.util.ArrayList[1]->org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem["caption"]->org.brunocvcunha.instagram4j.requests.payload.InstagramComment["pk"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
        at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141)
        at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
        at org.brunocvcunha.instagram4j.requests.InstagramTimelineFeedRequest.parseResult(InstagramTimelineFeedRequest.java:58)
        at org.brunocvcunha.instagram4j.requests.InstagramTimelineFeedRequest.parseResult(InstagramTimelineFeedRequest.java:29)
        at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:56)
        at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281)
        at org.brunocvcunha.instagram4j.Instagram4j.emulateUserLoggedIn(Instagram4j.java:296)
        at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:211)

**Comment by jemand771** [comment]
Duplicate to #310 and #301

**Comment by jemand771** [comment]
This is a kind-of-known issue and has occured with some posts before. Please post your code or steps to reproduce.
Set the logging output of the library to `DEBUG` and post a full log. Note that this may expose private information such as who you follow.

**Comment by k1ll1n** [comment]
+1

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `long` from String "2053030726316866006_caption": not a valid Long value
 at [Source: (StringReader); line: 1, column: 23650] (through reference chain: org.brunocvcunha.instagram4j.requests.payload.InstagramFeedResult["items"]->java.util.ArrayList[5]->org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem["caption"]->org.brunocvcunha.instagram4j.requests.payload.InstagramComment["pk"])
```

```kotlin
    val instagram = Instagram4j.builder()
        .username(login)
        .password(password)
        .build()
    instagram.setup()
    instagram.login() // Error here
```

**Comment by jemand771** [comment]
mediaId doesn't seem to be of type long as defined, but String.
We could just change the datatype to String, but that would definitely break some things. (Such as clientside shortcode<->mediaId conversion)

I'm curious why it sometimes works and sometimes doesn't 🤔

**Comment by jemand771** [comment]
Albums. It's albums.
The error described only happens if a post has more than one photo/video. (Those left/right-slidy things)

I'll try to understand how albums work and create a (reasonable) fix for this.

**Comment by jemand771** [comment]
Changing the field `pk` inside of `InstagramComment` from `long` to `String` seems to fix this particular issue. Though, I don't feel comfortable with that at all.
Maybe there are other cases that even require changes to `InstagramFeedItem`. And as said before, I somehow think that this will break stuff.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
