### ISSUE TITLE
Unrecognized token 'Request': was expecting ('true', 'false' or 'null') while doing feed pagination.

### ISSUE THREAD

**Issue by Johnny850807** [instagram4j/instagram4j#368]
After log-in the instagram4j

```java
@Override
    public Collection<TargetFeed> getFeeds(int number) throws IOException {
        Collection<InstagramFeedItem> items = new ArrayList<>(number);
        InstagramFeedResult result = session.sendRequest(new InstagramUserFeedRequest(instagramUser.getPk()));

        do {
            items.addAll(result.getItems().subList(0, Math.min(number, result.getItems().size())));
            number -= result.getItems().size();
            if (result.isMore_available())
                result = session.sendRequest(new InstagramUserFeedRequest(instagramUser.getPk(), result.getNext_max_id(), 0, Long.MAX_VALUE));
        } while(number > 0);

        return feedItemsToTargetFeeds(items);
}
```

The code above causes the exception.

**Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Request': was expecting ('true', 'false' or 'null')**
 at [Source: (String)"Request Timeout"; line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4142)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
	at org.brunocvcunha.instagram4j.requests.InstagramUserFeedRequest.parseResult(InstagramUserFeedRequest.java:50)
	at org.brunocvcunha.instagram4j.requests.InstagramUserFeedRequest.parseResult(InstagramUserFeedRequest.java:31)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:56)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281)
	at com.teampathy.impl.TargetUserAdapter.getFeeds(Instagram4Js.java:145)
	at com.teampathy.base.Instagram$InstagramSession$TargetUser.foreachFeed(Instagram.java:83)
	at com.teampathy.impl.Main.main(Instagram4Js.java:277)

**Comment by iWhiver** [comment]
Same problem in new version 1.12, but in 1.10 everything working.

**Comment by jemand771** [comment]
adding this for context
```
2019-08-19 13:42:40 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramUserFeedRequest
2019-08-19 13:42:40 [main] DEBUG org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramFeedResult from Request Timeout
```
No JSON is sent back from the API, just "Request Timeout"
This only occurs when using `InstagramUserFeedRequest` with a `next_max_id`, the userId-only call still works fine.

**Comment by jemand771** [comment]
Well, if you just put 0 for both `minTimestamp `and `maxTimestamp`, it works fine.
I don't think these parameters even do anything serverside. Maybe we should just ditch them in a future release.

**Comment by iWhiver** [comment]
Yes, it's works

**Comment by Johnny850807** [comment]
> put 0 for both minTimestamp and maxTimestamp
This solves the problem.

**Comment by m3hdiii** [comment]
> Well, if you just put 0 for both `minTimestamp `and `maxTimestamp`, it works fine.
> I don't think these parameters even do anything serverside. Maybe we should just ditch them in a future release.

How ? 
There is no timeout under Instagram Object

**Comment by m3hdiii** [comment]
> Same problem in new version 1.12, but in 1.10 everything working.

It's not working in version 1.10 also

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
