### ISSUE TITLE
Problem with video uploading

### ISSUE THREAD

**Issue by acunm** [instagram4j/instagram4j#388]
This is an error I get when I try to upload a video. Image uploading works fine, I tried different 3 different videos and all they gave same error. What may cause this error?

> Exception in thread "Thread-18" java.lang.IllegalStateException: Failed uploading video (400): Something is wrong. Please check your input and try again.
	at org.brunocvcunha.instagram4j.requests.internal.InstagramUploadVideoJobRequest.execute(InstagramUploadVideoJobRequest.java:121)
	at org.brunocvcunha.instagram4j.requests.internal.InstagramUploadVideoJobRequest.execute(InstagramUploadVideoJobRequest.java:41)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:101)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281)
	at App.APIClasses.Instagram.postVideo(Instagram.java:53)
	at App.UIControllers.Controller.lambda$initialize$3(Controller.java:102)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by TLHP** [comment]
I have the same message "Something is wrong. Please check your input and try again." when uploading images.

**Comment by veryevilzed** [comment]
Problem with Photo Upload

019-10-31 08:49:50 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest
2019-10-31 08:49:50 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - URL Upload: https://i.instagram.com/api/v1/upload/photo/
2019-10-31 08:49:51 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - Photo Upload result: 400, Something is wrong. Please check your input and try again.
2019-10-31 08:49:51 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramConfigurePhotoResult from Something is wrong. Please check your input and try again.

**Comment by AuligPromotions** [comment]
Yea, I'm getting that too now (with images).

**Comment by TLHP** [comment]
It worked now, I don't know why :D

**Comment by AleTassi** [comment]
News about what happened?  I'm still getting this error :(

**Comment by Kaktushose** [comment]
same, have this error since today

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
