### ISSUE TITLE
Problem with Stories

### ISSUE THREAD

**Issue by gss0** [instagram4j/instagram4j#389]
This is the error I get when try to create a new IG story. Until 4 days ago everything was ok.

```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Something': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Something is wrong. Please check your input and try again."; line: 1, column: 10]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4142)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
        at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141)
        at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
        at org.brunocvcunha.instagram4j.requests.InstagramUploadStoryPhotoRequest.parseResult(InstagramUploadStoryPhotoRequest.java:160)
        at org.brunocvcunha.instagram4j.requests.InstagramUploadStoryPhotoRequest.execute(InstagramUploadStoryPhotoRequest.java:96)
        at org.brunocvcunha.instagram4j.requests.InstagramUploadStoryPhotoRequest.execute(InstagramUploadStoryPhotoRequest.java:46)
        at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281)
        at com.cartamoneta.server.controller.GestioneInstagramCONTROLLER.inviaStoriaRandom(GestioneInstagramCONTROLLER.java:174)
```

**Comment by gss0** [comment]
Any fix for this? Since about 10 days the problem is again here.

We are unable to post pics or stories.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
