### ISSUE TITLE
Can't login (java.lang.RuntimeException: Error happened in photo upload: login_required)

### ISSUE THREAD

**Issue by uku3lig** [instagram4j/instagram4j#421]
```java
Exception in thread "main" java.lang.RuntimeException: Error happened in photo upload: login_required
	at org.brunocvcunha.instagram4j.requests.InstagramUploadStoryPhotoRequest.execute(InstagramUploadStoryPhotoRequest.java:99)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadStoryPhotoRequest.execute(InstagramUploadStoryPhotoRequest.java:46)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281)
	at net.uku3lig.postbot.Main.post(Main.java:62)
	at net.uku3lig.postbot.Main.main(Main.java:38)
```

the code used:
```java
instagram = Instagram4j.builder()
				 .username("username")
				 .password("password")
				 .build();
		 instagram.setup();
		 instagram.login();
/* ... */
File img = new File("image.png");
InstagramUploadStoryPhotoRequest req = new InstagramUploadStoryPhotoRequest(img);
instagram.sendRequest(req);
```

**Comment by Suzanskiy** [comment]
Have you specified login and password of your account ? I guess have no

**Comment by uku3lig** [comment]
Yes i did. I just removed them in this code.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
