### ISSUE TITLE
Cannot upload photo

### ISSUE THREAD

**Issue by barreeeiroo** [instagram4j/instagram4j#433]
The following error happens when trying to upload a photo:

```
2020-04-01 13:31:37 [main] INFO  org.brunocvcunha.instagram4j.Instagram4j  - Sending request: org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest
2020-04-01 13:31:38 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - URL Upload: https://i.instagram.com/api/v1/upload/photo/
2020-04-01 13:31:39 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest  - Photo Upload result: 400, Something is wrong. Please check your input and try again.
2020-04-01 13:31:39 [main] INFO  org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramConfigurePhotoResult from Something is wrong. Please check your input and try again.
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Something': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Something is wrong. Please check your input and try again."; line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4142)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:141)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRequest.java:111)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.parseResult(InstagramUploadPhotoRequest.java:171)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:106)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:44)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:281)
	at xyz.barreiro.ig.bot.InstagramWarBot.main(InstagramWarBot.java:23)
```

Code:

```
Instagram4j instagram = Instagram4j.builder().username("********").password("********").build();
instagram.setup();
instagram.login();

instagram.sendRequest(new InstagramUploadPhotoRequest(
    new File("C:/Github/InstagramJavaBot/media/test2.jpg"),
    "Testing..."));
```

**Comment by schreibermm** [comment]
Same issue.

**Comment by schreibermm** [comment]
You need to upgrade dependency version to 1.14.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
