### ISSUE TITLE
can't use the library

### ISSUE THREAD

**Issue by AndreaRiboni** [instagram4j/instagram4j#458]
When trying to run a project which is using this external JAR, i get the "java.lang.NoClassDefFoundError: org/apache/http/client/CookieStore" error.

While Maven won't even compile.

**Comment by jxin19** [comment]
let me see all of stacktrace

**Comment by AndreaRiboni** [comment]
> let me see all of stacktrace

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/CookieStore
	at instagrambot.Bot.<init>(Bot.java:11)
	at instagrambot.InstagramBot.main(InstagramBot.java:16)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.CookieStore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
C:\Users\Utente\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by jxin19** [comment]
@AndreaRiboni 
above stacktrace information is not enough.
anyway clean the project and build again.
or check maven(or gradle) configuration file about line53 of run.xml.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
