### ISSUE TITLE
No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier

### ISSUE THREAD

**Issue by HMY314** [instagram4j/instagram4j#466]
instagram.setup()

implementation 'org.brunocvcunha.instagram4j:instagram4j:1.14'

Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:977)
        at org.brunocvcunha.instagram4j.Instagram4j.setup(Instagram4j.java:199)

**Comment by aleradamantis99** [comment]
I have the same problem. Did you find any solution?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
