### ISSUE TITLE
MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token

### ISSUE THREAD

**Issue by hooldj** [instagram4j/instagram4j#485]
Code that trying to print messages from direct:

```
public MessagesList(IGClient client, IGThread thread){

            thread.getItems().forEach(threadItem->{
                try {
                    DirectThreadsResponse inboxThread = client.sendRequest(new DirectThreadsRequest(thread.getThread_id()));

                        inboxThread.getThread().getItems().forEach(threadItem1->{
                            System.out.println(threadItem1.getItem_type());
                        });
                } catch (IOException e) {
                    e.printStackTrace();
                }
            });
    }
```
Error log:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"{"thread": {"thread_id": "thread_id", "thread_v2_id": "17873302081828739", "users": [{"pk": 7218769496, "username": "usernameHiden", "full_name": "fullNameHiden", "is_private": false, "profile_pic_url": "picUrlHiden", "profile_pic_id": "12345"[truncated 8100 chars]; line: 1, column: 4958] (through reference chain: com.github.instagram4j.instagram4j.responses.direct.DirectThreadsResponse["thread"]->com.github.instagram4j.instagram4j.models.direct.IGThread["items"]->java.util.ArrayList[10]->com.github.instagram4j.instagram4j.models.direct.item.ThreadRavenMediaItem["visual_media"]->com.github.instagram4j.instagram4j.models.direct.item.ThreadRavenMediaItem$ThreadVisualMedia["seen_user_ids"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1464)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1238)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:714)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:40)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:132)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1197)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at com.github.instagram4j.instagram4j.utils.IGUtils.jsonToObject(IGUtils.java:245)
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:69)
	at com.github.instagram4j.instagram4j.IGClient.sendRequest(IGClient.java:124)
	at com.github.instagram4j.instagram4j.IGClient.sendRequest(IGClient.java:110)
	at MessagesList.lambda$new$1(MessagesList.java:19)

**Comment by jvogit** [comment]
Thank you for your report! 

I've narrowed it down to [this field](https://github.com/instagram4j/instagram4j/blob/066efc796f87836718c4f99b1c8fa04ec82921a5/src/main/java/com/github/instagram4j/instagram4j/models/direct/item/ThreadRavenMediaItem.java#L18) being a String type when it should a List<String>.

**Comment by jvogit** [comment]
The fix will be pushed in the next weekly develop build. If you want to keep up with a snapshot of the develop branch, see here to add [jitpack](https://github.com/instagram4j/instagram4j#example-for-gradle-1).
