### ISSUE TITLE
IGLoginException

### ISSUE THREAD

**Issue by FirstVoyager** [instagram4j/instagram4j#489]
## IGLoginException

`com.github.instagram4j.instagram4j.exceptions.IGLoginException: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at com.github.instagram4j.instagram4j.IGClient$Builder.performLogin(IGClient.java:277)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:240)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:247)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at limitless.android.i.unfollowtita.Activity.MainActivity.main(MainActivity.java:64)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at limitless.android.i.unfollowtita.Activity.MainActivity$login.doInBackground(MainActivity.java:79)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at limitless.android.i.unfollowtita.Activity.MainActivity$login.doInBackground(MainActivity.java:74)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:316)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2020-09-02 20:26:49.392 9672-9700/limitless.android.i.unfollowtita W/System.err:     at java.lang.Thread.run(Thread.java:776)`

## Gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "limitless.android.i.unfollowtita"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // local
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    // appcompat
    implementation 'androidx.appcompat:appcompat:1.2.0'
    // test
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    // any chart
    implementation 'com.github.AnyChart:AnyChart-Android:1.1.2'
    // multi dex
    implementation 'androidx.multidex:multidex:2.0.1'
    // retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.8.1'
    // gson
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    // admob
    implementation 'com.google.android.gms:play-services-ads:19.3.0'
    // material
    implementation 'com.google.android.material:material:1.3.0-alpha02'
    // instagram4j
    implementation 'com.github.instagram4j:instagram4j:develop-SNAPSHOT'
    // OkHttp
    implementation 'com.squareup.okhttp3:okhttp:4.7.2'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.7.2'
    // jackson data-bind
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.11.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.11.0'
    implementation 'org.slf4j:slf4j-api:1.7.30'
    // Internal utilities
    implementation 'commons-codec:commons-codec:1.5'
}

**Comment by jvogit** [comment]
Make sure dependencies are included at runtime. It seems it cannot find commons codec at runtime. Though I do realize that the entire commons codec dependency may not be necessary and I may just include the few methods I use along with the build.

**Comment by jvogit** [comment]
Next develop build will remove apache commons codec dependency.
