### ISSUE TITLE
How to handle IGResponseException

### ISSUE THREAD

**Issue by LukaskzB** [instagram4j/instagram4j#508]
I made sure...
- [x] I read the README.md
- [X] I looked over the examples and wiki
- [X] my issue hasn't been asked or solved before

---

### Question

How to handle the IGResponseException?
My code: `MediaCommentRequest request = new MediaCommentRequest(mediaid, comment);
		instagram.sendRequest(request).join();`
Error: `Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: failed to mention
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:85)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:151)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:135)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException: failed to mention
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:148)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 7 more
`

**Comment by LukaskzB** [comment]
Just add try{ code }catch(Exception e){ now handle it}
