### ISSUE TITLE
Getting 400 response when trying to upload a photo

### ISSUE THREAD

**Issue by uku3lig** [instagram4j/instagram4j#520]
I log in correctly, i tried some other requests (getting the profile picture of an user) and everything worked perfeclty fine.
But when i try to upload a photo, an IGResponseException is thrown, and the logs show that the request returned a 400 response.
I tried using a File, a byte array, dooing the request 10 seconds after login, simulate the login, but none of them worked.
My code 
```java
try {
            IGClient instagram = IGClient.builder()
                    .username("********")
                    .password("********")
                    .onTwoFactor(twoFactorHandler)
                    .onChallenge(challengeHandler)
                    .simulatedLogin();
            System.out.println("Logged into instagram");
            new Timer().schedule(new TimerTask() {
                @SneakyThrows
                @Override
                public void run() {
                    FileInputStream fis = new FileInputStream("yeet.png");
                    instagram.actions()
                            .timeline()
                            .uploadPhoto(fis.readAllBytes(), "caption")
                            .thenAccept(r -> System.out.println("uploaded lol"))
                            .join();
                }
            }, 10000);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("NOOOOOOOOOOOOOOOO");
        }
```
Logs
```
> Task :Main.main()
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://b.i.instagram.com/api/v1/launcher/sync/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://b.i.instagram.com/api/v1/qe/sync/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://b.i.instagram.com/api/v1/accounts/contact_point_prefill/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://b.i.instagram.com/api/v1/accounts/get_prefill_candidates/
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/accounts/contact_point_prefill/ : 200
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/accounts/contact_point_prefill/ with body (truncated) : {"status": "ok"}
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/accounts/get_prefill_candidates/ : 200
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/accounts/get_prefill_candidates/ with body (truncated) : {"prefills": [{"usage": "account_recovery_omnibox", "candidates": []}], "status": "ok"}
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/launcher/sync/ : 200
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/qe/sync/ : 200
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/launcher/sync/ with body (truncated) : {"configs": {"ig_android_carrier_signals_killswitch": {"params": {"is_enabled": {"value": true}}}, "
[OkHttp https://b.i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://b.i.instagram.com/api/v1/qe/sync/ with body (truncated) : {"experiments": [{"name": "ig_android_direct_add_direct_to_android_native_photo_share_sheet", "group
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/qe/sync/
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ with body (truncated) : {"experiments": [{"name": "ig_android_shopping_checkout_signaling", "group": "rollout", "additional_
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/accounts/login/
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ with body (truncated) : {"logged_in_user": {"pk": 6880148876, "username": "uku3lig", "full_name": "", "is_private": true, "p
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Logged into uku3lig (6880148876)
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/launcher/sync/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/qp/get_cooldowns/?signature=signed_body%3DSIGNATURE.%257B%257D
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/multiple_accounts/get_account_family/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/linked_accounts/get_linkage_status/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/loom/fetch_config/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/media/blocked/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/feed/timeline/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/feed/reels_tray/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/users/arlink_download_info/?version_override=2.2.1
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/discover/topical_explore/?max_id=0&is_prefetch=true&module=explore_popular&use_sectional_payload=true&omit_cover_media=true&session_id=ab83a65d-5903-4e4e-989d-706cea7b1e70
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/news/inbox/?mark_as_seen=false
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/direct_v2/get_presence/
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/direct_v2/inbox/?visual_message_return_type=unseen&limit=0&persistent_badging=true
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/direct_v2/inbox/?visual_message_return_type=unseen&thread_message_limit=10&limit=20&persistent_badging=true&fetch_reason=initial_snapshot
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/status/get_viewable_statuses/
Logged into instagram
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qp/get_cooldowns/?signature=signed_body%3DSIGNATURE.%257B%257D : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qp/get_cooldowns/?signature=signed_body%3DSIGNATURE.%257B%257D with body (truncated) : {"ttl": 604800, "global": 0, "default": 1200, "surfaces": [{"surface_id": 4715, "cooldown": 1200}, {
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/multiple_accounts/get_account_family/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/multiple_accounts/get_account_family/ with body (truncated) : {"child_accounts": [], "main_accounts": [], "current_account": {"pk": 6880148876, "username": "uku3l
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/loom/fetch_config/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/loom/fetch_config/ with body (truncated) : {"status": "ok"}
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/linked_accounts/get_linkage_status/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/linked_accounts/get_linkage_status/ with body (truncated) : {"linkage": {"facebook": {"is_linked": true, "name": "Yet Yet", "fbid": "100046517226574", "error_co
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/media/blocked/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/media/blocked/ with body (truncated) : {"media_ids": [], "status": "ok"}
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/users/arlink_download_info/?version_override=2.2.1 : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/users/arlink_download_info/?version_override=2.2.1 with body (truncated) : {"checksum": "c56dbc151cb78f1d6fcea075d6bce5e5c44d8e57b880797ef76f33944d2752a4", "download_url": "ht
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/launcher/sync/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/feed/reels_tray/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/feed/reels_tray/ with body (truncated) : {"tray": [{"id": 6880148876, "latest_reel_media": 1603974340, "expiring_at": 1604060740, "seen": 160
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/launcher/sync/ with body (truncated) : {"configs": {"ig_android_ad_platform_funnel_logging": {"params": {"is_enabled_stories": {"value": fa
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/direct_v2/inbox/?visual_message_return_type=unseen&limit=0&persistent_badging=true : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/direct_v2/inbox/?visual_message_return_type=unseen&limit=0&persistent_badging=true with body (truncated) : {"pending_requests_total": 0, "has_pending_top_requests": true, "should_hide_message_preview": false
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/news/inbox/?mark_as_seen=false : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/news/inbox/?mark_as_seen=false with body (truncated) : {"aymf": {"items": [{"user": {"pk": "10337732900", "username": "em_bnt", "full_name": "emma", "is_pr
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/direct_v2/get_presence/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/direct_v2/get_presence/ with body (truncated) : {"user_presence": {"35158101376": {"is_active": false, "last_activity_at_ms": 1604050165202}, "40266
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/status/get_viewable_statuses/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/status/get_viewable_statuses/ with body (truncated) : {"statuses": {}, "status": "ok"}
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/feed/timeline/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/feed/timeline/ with body (truncated) : {"num_results": 7, "more_available": true, "auto_load_more_enabled": true, "feed_items": [{"media_or
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/discover/topical_explore/?max_id=0&is_prefetch=true&module=explore_popular&use_sectional_payload=true&omit_cover_media=true&session_id=ab83a65d-5903-4e4e-989d-706cea7b1e70 : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/discover/topical_explore/?max_id=0&is_prefetch=true&module=explore_popular&use_sectional_payload=true&omit_cover_media=true&session_id=ab83a65d-5903-4e4e-989d-706cea7b1e70 with body (truncated) : {"sectional_items": [{"layout_type": "one_by_two_left", "layout_content": {"one_by_two_item": {"clip
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/direct_v2/inbox/?visual_message_return_type=unseen&thread_message_limit=10&limit=20&persistent_badging=true&fetch_reason=initial_snapshot : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/direct_v2/inbox/?visual_message_return_type=unseen&thread_message_limit=10&limit=20&persistent_badging=true&fetch_reason=initial_snapshot with body (truncated) : {"viewer": {"pk": 6880148876, "username": "uku3lig", "full_name": "", "is_private": true, "profile_p
[Timer-0] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/rupload_igphoto/1604057130401_0_5413576662
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604057130401_0_5413576662 : 400
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604057130401_0_5413576662 with body (truncated) : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed
Exception in thread "Timer-0" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:86)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:152)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:136)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException

	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:149)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 7 more
```

**Comment by aosamaRada** [comment]
same thing here 
my code 
 IGClient client = IGClient.builder()
                    .username("*****")
                    .password("*****")
                    .login();
            client.actions()
                    .timeline()
                    .uploadPhoto(thumbnail, "My Caption #java")
                    .thenAccept(response -> {
                        System.out.println("Successfully uploaded photo!");
                    })
                    .join();


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:86)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:152)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:136)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:149)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException

	... 7 more

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by jvogit** [comment]
If this issue is reproducible, can you please enable DEBUG level logging and log the full JSON response. As far as I know, it is still working. The truncated response indicated the photo upload has failed. Please make sure the photo is within acceptable dimensions for Instagram.

**Comment by NxDs** [comment]
Having the same issue only when uploading photos (or albums), everything else works but upload throws an exception
```
Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:86)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:152)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:884)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:866)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:136)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:149)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	... 7 more
```

And this is the log data
```
11:24:18.765 [main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/rupload_igphoto/1604917458756_0_6670466801
11:24:18.833 [main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/rupload_igphoto/1604917458832_0_8832262046
11:24:18.833 [main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/rupload_igphoto/1604917458833_0_2168694099
11:24:18.835 [main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/rupload_igphoto/1604917458835_0_7205570840
11:24:18.836 [main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/rupload_igphoto/1604917458836_0_3318497686
11:24:19.447 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458756_0_6670466801 : 400
11:24:19.450 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458756_0_6670466801 with body : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
11:24:19.451 [OkHttp https://i.instagram.com/...] DEBUG com.github.instagram4j.instagram4j.requests.IGRequest - rupload_igphoto/1604917458756_0_6670466801 parsing response : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
11:24:19.869 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458835_0_7205570840 : 200
11:24:19.869 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458835_0_7205570840 with body : {"upload_id": "1604917458746", "xsharing_nonces": {}, "status": "ok"}
11:24:19.869 [OkHttp https://i.instagram.com/...] DEBUG com.github.instagram4j.instagram4j.requests.IGRequest - rupload_igphoto/1604917458835_0_7205570840 parsing response : {"upload_id": "1604917458746", "xsharing_nonces": {}, "status": "ok"}
11:24:19.886 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458836_0_3318497686 : 500
11:24:19.886 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458836_0_3318497686 with body : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
11:24:19.886 [OkHttp https://i.instagram.com/...] DEBUG com.github.instagram4j.instagram4j.requests.IGRequest - rupload_igphoto/1604917458836_0_3318497686 parsing response : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
11:24:19.902 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458832_0_8832262046 : 200
11:24:19.903 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458832_0_8832262046 with body : {"upload_id": "1604917458745", "xsharing_nonces": {}, "status": "ok"}
11:24:19.903 [OkHttp https://i.instagram.com/...] DEBUG com.github.instagram4j.instagram4j.requests.IGRequest - rupload_igphoto/1604917458832_0_8832262046 parsing response : {"upload_id": "1604917458745", "xsharing_nonces": {}, "status": "ok"}
11:24:19.909 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458833_0_2168694099 : 500
11:24:19.910 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1604917458833_0_2168694099 with body : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
11:24:19.910 [OkHttp https://i.instagram.com/...] DEBUG com.github.instagram4j.instagram4j.requests.IGRequest - rupload_igphoto/1604917458833_0_2168694099 parsing response : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
```

The whole JSON response I'm getting is 
`{"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}`

Login and retrieving other kind of data however works fine

**Comment by jvogit** [comment]
Hi please make sure your photos are within acceptable dimensions for Instagram. If possible could you provide the photos that are causing the issue? It seems some photos work while others do not in your logs. I cannot reproduce the issue on my end.

**Comment by NxDs** [comment]
Thank you, that was indeed the issue I was not meeting the minimum image size apparently.
Now I'm resizing images up to 800x800 and squaring them for good measure and it seems to be working properly.

Although I feel like it might be worth mentioning somewhere in wiki or javadocs that images should meet certain standards in order to be uploaded

**Comment by jvogit** [comment]
I will make a note of this. For now and future reference

here is the Instagram article detailing what dimensions are allowed.

[Article](https://help.instagram.com/1631821640426723)

**Comment by NxDs** [comment]
I think it's also worth mentioning that PNG images are rejected as well regardless the size requirements, I suspect that might have to do with the fact they have the alpha channel and Instagram doesn't support that, or the PNG format altogether specifically using BufferedImage.TYPE_INT_ARGB at least from my tests.

**Comment by prateek-resiliencesoft** [comment]
Does its solve your issue @NxDs ?
I have changed image size & everything but still getting same response
{"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}

**Comment by NxDs** [comment]
Yes for me the issue was the image size and the image format, this is the method I made to normalize images and make them squared, at least 800x800 and RGB format

```java
public BufferedImage squareImage(BufferedImage image, int type) {
        if (image.getWidth() == image.getHeight() && image.getWidth() >= 800  && image.getType() == type) return image;

        int size = Math.max(800, Math.max(image.getWidth(), image.getHeight()));
        BufferedImage res = new BufferedImage(size, size, type);
        Graphics2D g2 = res.createGraphics();

        double ratio = size / (double) (Math.max(image.getWidth(), image.getHeight()));
        int width = (int) (image.getWidth() * ratio);
        int height = (int) (image.getHeight() * ratio);

        g2.drawImage(image, res.getWidth() / 2 - width / 2, res.getHeight() / 2 - height / 2, width, height, null);
        g2.dispose();

        return res;
    }
```
And to use it
`squareImage(image, BufferedImage.TYPE_INT_RGB)`
Although it should be noted that there's most likely a maximum size for the images that instagram can allow, the method I just provided doesn't take that into account as it only scales up small images

I'm also not entirely sure if squaring the image is a requirement but since it suits my purpose I do that too, note that it doesn't simply square the image it keeps the ratio and simply adds black bands either on top or on the sides depending on the original ratio, you may rework my method to fit your needs 

Also note that 800 pixels is an arbitrary size I used that worked for me, the minimum limit might be smaller than that tho I suppose unless there's a clearer API specification somewhere it will require some trial and error

**Comment by prateek-resiliencesoft** [comment]
@NxDs thanks for your quick response

**Comment by mhorizon** [comment]
hi i have same problem and none of above approach worked for me!
previous version (1.x.x) upload photo but new release (2.x.x) not uploading same photo
please help me!!!

**Comment by MrEAlderson** [comment]
> hi i have same problem and none of above approach worked for me!
> previous version (1.x.x) upload photo but new release (2.x.x) not uploading same photo
> please help me!!!

https://github.com/instagram4j/instagram4j/issues/564#issuecomment-819816701
