### ISSUE TITLE
Could not use instagram4j with Spring Boot Applications: java.lang.NoClassDefFoundError: okhttp3/OkHttpClient

### ISSUE THREAD

**Issue by m-tsybulskyi-git** [instagram4j/instagram4j#532]
### Describe the bug
Could not use instagram4j with Spring Boot Applications

### How to reproduce
Create Spring Boot Application with this source code

#### Source code
pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.github.instagram4j</groupId>
			<artifactId>instagram4j</artifactId>
			<version>2.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>5.2.9.RELEASE</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

```

InstagramService.java
```java

package com.example.demo;

import com.github.instagram4j.instagram4j.IGClient;
import com.github.instagram4j.instagram4j.exceptions.IGLoginException;
import org.springframework.stereotype.Service;

@Service
public class InstagramService {
    IGClient client;
    String username = "-USERNAME-";
    String password = "-PASSWORD-";

    InstagramService() throws IGLoginException {
        client = IGClient.builder()
                .username(username)
                .password(password)
                .login();
    }
}
```

Application.java
```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```
### Actual behavior
```
2020-11-22 11:59:06.455  WARN 19276 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instagramService' defined in file [...]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.demo.InstagramService]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: okhttp3/Callback

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instagramService' defined in file [...]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.demo.InstagramService]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: okhttp3/Callback
...
Caused by: java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
	at com.github.instagram4j.instagram4j.IGClient$Builder.build(IGClient.java:233) ~[instagram4j-2.0.0.jar:na]
	at com.github.instagram4j.instagram4j.IGClient$Builder.login(IGClient.java:253) ~[instagram4j-2.0.0.jar:na]
	at com.mtysbulskyi.commentbot.service.InstagramService.<init>(InstagramService.java:28) ~[classes/:na]
	at com.mtysbulskyi.commentbot.botapi.handlers.StartHandler.<init>(StartHandler.java:15) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 53 common frames omitted
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 63 common frames omitted
```

**Comment by jvogit** [comment]
Hi,

this is the same issue as #533 so I am closing this one for discussion on there for both springboot and quarkus.

In short, springboot and quarkus use okhttp 3.x while this project uses okhttp 4.x Try upgrading the binaries if at all possible.

**Comment by khale11** [comment]
ماذا نفعل

**Comment by GehadG** [comment]
in the gradle file use 
    implementation ('com.squareup.okhttp3:okhttp:4.7.2') {
        force = true
    }
    implementation('com.squareup.okhttp3:okhttp-urlconnection:4.7.2'){
        force = true
    }
