### ISSUE TITLE
Not compatible with Quarkus: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

### ISSUE THREAD

**Issue by helightdev** [instagram4j/instagram4j#533]
`2020-11-22 19:25:12,297 INFO  [com.git.ins.ins.IGClient] (Quarkus Main Thread) Sending request : https://i.instagram.com/api/v1/qe/sync/
2020-11-22 19:25:12,334 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at com.github.instagram4j.instagram4j.requests.IGPostRequest.getRequestBody(IGPostRequest.java:41)
Caused by: java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'

	at com.github.instagram4j.instagram4j.requests.IGPostRequest.formRequest(IGPostRequest.java:27)
	at com.github.instagram4j.instagram4j.IGClient.sendRequest(IGClient.java:125)
	at com.github.instagram4j.instagram4j.requests.IGRequest.execute(IGRequest.java:48)
	at com.github.instagram4j.instagram4j.IGClient.sendLoginRequest(IGClient.java:97)
	at com.github.instagram4j.instagram4j.IGClient$Builder.performLogin(IGClient.java:261)
	at com.github.instagram4j.instagram4j.IGClient$Builder.login(IGClient.java:255)
	at org.acme.commandmode.HelloCommando.run(HelloCommando.kt:16)
	at org.acme.commandmode.HelloCommando_ClientProxy.run(HelloCommando_ClientProxy.zig:156)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:117)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
	... 6 more`

Gradle:
`plugins {
    id 'org.jetbrains.kotlin.jvm' version "1.3.72"
    id "org.jetbrains.kotlin.plugin.allopen" version "1.3.72"
    id 'io.quarkus'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url 'https://jitpack.io'
    }
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

    implementation 'com.github.instagram4j:instagram4j:2.0.0'

    implementation 'io.quarkus:quarkus-mongodb-panache'
    implementation 'io.quarkus:quarkus-resteasy-jsonb'
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'io.quarkus:quarkus-arc'

    testImplementation 'io.quarkus:quarkus-junit5'
}

group 'dev.helight.instamob'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

quarkus {
    setOutputDirectory("$projectDir/build/classes/kotlin/main")
}

quarkusDev {
    setSourceDir("$projectDir/src/main/kotlin")
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

compileKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11
    kotlinOptions.javaParameters = true
}

compileTestKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11
}
`

EntryPoint:
`package org.acme.commandmode

import com.github.instagram4j.instagram4j.IGClient
import javax.inject.Inject

import io.quarkus.runtime.QuarkusApplication
import io.quarkus.runtime.annotations.QuarkusMain

@QuarkusMain
class HelloCommando: QuarkusApplication {

    override fun run(vararg args: String?): Int {
        var client = IGClient.builder()
                .username("-")
                .password("-")
                .login()

        return 0
    }

}
`

I'm using a fresh copy of the auto-generated kotlin template for quarkus using gradle, so this should be quite easy to reproduce.

**Comment by helightdev** [comment]
It seems like the OkHttp version used here is pretty much incompatible with frameworks like quarkus and spring

**Comment by jvogit** [comment]
Hi yes, from quick research it seems springboot and quarkus add okhttp 3.x version. This project uses okhttp 4.x

I think it should be possible to use okhttp 4.x binaries with springboot or quarkus or perhaps not?

**Comment by m-tsybulskyi-git** [comment]
I resolved this problem by adding okhttp dependencies to my gradle project, and all working fine with that

```xml
...
dependencies {
    ...
    api 'com.squareup.okhttp3:okhttp:4.7.2'
    api 'com.squareup.okhttp3:okhttp-urlconnection:4.7.2'
}
...
```

**Comment by helightdev** [comment]
Already tried that, my dependencies are ```dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")

    implementation 'com.github.instagram4j:instagram4j:2.0.0'

    implementation 'io.quarkus:quarkus-mongodb-panache'
    implementation 'io.quarkus:quarkus-resteasy-jsonb'
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'io.quarkus:quarkus-arc'

    api 'com.squareup.okhttp3:okhttp:4.7.2'
    api 'com.squareup.okhttp3:okhttp-urlconnection:4.7.2'

    testImplementation 'io.quarkus:quarkus-junit5'
}``` 
But it still throws the same Error

**Comment by helightdev** [comment]
[dependencies.log](https://github.com/instagram4j/instagram4j/files/5585956/dependencies.log)
This is my dependency tree. It seems gradle is changing the version back even though I changed the dependencies. Any ideas?

**Comment by GehadG** [comment]
in your build.gradle 
    implementation ('com.squareup.okhttp3:okhttp:4.7.2') {
        force = true
    }
    implementation('com.squareup.okhttp3:okhttp-urlconnection:4.7.2'){
        force = true
    }

**Comment by helightdev** [comment]
Okay this fixes the wrong okhttp version 
```
Executing tasks 'dependencyInsight --dependency okhttp3 --quiet'...

com.squareup.okhttp3:okhttp:4.7.2
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - Forced
      - By constraint

com.squareup.okhttp3:okhttp:4.7.2
+--- compileClasspath
+--- com.github.instagram4j:instagram4j:2.0.0
|    \--- compileClasspath
\--- com.squareup.okhttp3:okhttp-urlconnection:4.7.2
     +--- compileClasspath
     \--- com.github.instagram4j:instagram4j:2.0.0 (*)

com.squareup.okhttp3:okhttp:3.14.9 -> 4.7.2
\--- io.quarkus:quarkus-universe-bom:1.9.2.Final
     \--- compileClasspath

com.squareup.okhttp3:okhttp-urlconnection:4.7.2 (forced)
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]

com.squareup.okhttp3:okhttp-urlconnection:4.7.2
+--- compileClasspath
\--- com.github.instagram4j:instagram4j:2.0.0
     \--- compileClasspath

(*) - dependencies omitted (listed previously)
```

But now I get some problems with okhttp and the kotlin-std in both Kotlin and Java projects
```
Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:71)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at com.github.instagram4j.instagram4j.utils.IGUtils.defaultHttpClientBuilder(IGUtils.java:215)
	at com.github.instagram4j.instagram4j.IGClient$Builder.lambda$build$1(IGClient.java:234)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
Caused by: java.lang.NoSuchFieldError: Companion

	at com.github.instagram4j.instagram4j.IGClient$Builder.build(IGClient.java:234)
	at com.github.instagram4j.instagram4j.IGClient$Builder.login(IGClient.java:253)
	at org.acme.commandmode.HelloCommando.run(HelloCommando.kt:16)
	at org.acme.commandmode.HelloCommando_ClientProxy.run(HelloCommando_ClientProxy.zig:156)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:117)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
	... 6 more

```

Am I supposed to open a new issue for this?

**Comment by jvogit** [comment]
> Okay this fixes the wrong okhttp version
> 
> ```
> Executing tasks 'dependencyInsight --dependency okhttp3 --quiet'...
> 
> com.squareup.okhttp3:okhttp:4.7.2
>    variant "compile" [
>       org.gradle.status                  = release (not requested)
>       org.gradle.usage                   = java-api
>       org.gradle.libraryelements         = jar (compatible with: classes)
>       org.gradle.category                = library
> 
>       Requested attributes not found in the selected variant:
>          org.gradle.dependency.bundling     = external
>          org.jetbrains.kotlin.platform.type = jvm
>          org.gradle.jvm.version             = 11
>    ]
>    Selection reasons:
>       - Forced
>       - By constraint
> 
> com.squareup.okhttp3:okhttp:4.7.2
> +--- compileClasspath
> +--- com.github.instagram4j:instagram4j:2.0.0
> |    \--- compileClasspath
> \--- com.squareup.okhttp3:okhttp-urlconnection:4.7.2
>      +--- compileClasspath
>      \--- com.github.instagram4j:instagram4j:2.0.0 (*)
> 
> com.squareup.okhttp3:okhttp:3.14.9 -> 4.7.2
> \--- io.quarkus:quarkus-universe-bom:1.9.2.Final
>      \--- compileClasspath
> 
> com.squareup.okhttp3:okhttp-urlconnection:4.7.2 (forced)
>    variant "compile" [
>       org.gradle.status                  = release (not requested)
>       org.gradle.usage                   = java-api
>       org.gradle.libraryelements         = jar (compatible with: classes)
>       org.gradle.category                = library
> 
>       Requested attributes not found in the selected variant:
>          org.gradle.dependency.bundling     = external
>          org.jetbrains.kotlin.platform.type = jvm
>          org.gradle.jvm.version             = 11
>    ]
> 
> com.squareup.okhttp3:okhttp-urlconnection:4.7.2
> +--- compileClasspath
> \--- com.github.instagram4j:instagram4j:2.0.0
>      \--- compileClasspath
> 
> (*) - dependencies omitted (listed previously)
> ```
> 
> But now I get some problems with okhttp and the kotlin-std in both Kotlin and Java projects
> 
> ```
> Error running Quarkus: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> Caused by: java.lang.NoSuchFieldError: Companion
> 	at okhttp3.internal.Util.<clinit>(Util.kt:71)
> 	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
> 	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
> 	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
> 	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
> 	at com.github.instagram4j.instagram4j.utils.IGUtils.defaultHttpClientBuilder(IGUtils.java:215)
> 	at com.github.instagram4j.instagram4j.IGClient$Builder.lambda$build$1(IGClient.java:234)
> 	at java.base/java.util.Optional.orElseGet(Optional.java:362)
> Caused by: java.lang.NoSuchFieldError: Companion
> 
> 	at com.github.instagram4j.instagram4j.IGClient$Builder.build(IGClient.java:234)
> 	at com.github.instagram4j.instagram4j.IGClient$Builder.login(IGClient.java:253)
> 	at org.acme.commandmode.HelloCommando.run(HelloCommando.kt:16)
> 	at org.acme.commandmode.HelloCommando_ClientProxy.run(HelloCommando_ClientProxy.zig:156)
> 	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:117)
> 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:62)
> 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
> 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
> 	... 6 more
> ```
> 
> Am I supposed to open a new issue for this?

I don't know if its totally relevant but here's what I found from the Slack SDK documentation (which also uses Okhttp 4.x) regarding Quarkus [here](https://slack.dev/java-slack-sdk/guides/supported-web-frameworks)

> After generating a blank project, remove quarkus-universe-bom from the build settings. The reason why we need to remove it is that, as of April 2020, quarkus-universe-bom adds okhttp 3.x to the project while this SDK requires okhttp 4.x. This means your application won’t work due to binary compatibility issues with the setting. If you cannot remove quarkus-universe-bom for some reasons, including Bolt for Java in the project may not be a feasible idea. Consider separating the application built with Bolt for Java from the one.

**Comment by grzegorz-aniol** [comment]
I also found such issue and I confirm what @jvogit said. Indeed, quarkus-universe-bom includes earlier okhttp version. Please check it out: 
[quarkus-universe-bom-1.13.3.Final.pom](https://repo1.maven.org/maven2/io/quarkus/quarkus-universe-bom/1.13.3.Final/quarkus-universe-bom-1.13.3.Final.pom)

I solved the issue with explicitly mentioned dependencies for okhttp3 but also specific version of okio:

```xml
       <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.1</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp-urlconnection</artifactId>
            <version>4.9.1</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okio</groupId>
            <artifactId>okio</artifactId>
            <version>2.8.0</version>
        </dependency>
```
I hope this will help you too.
