### ISSUE TITLE
Unable to login with proxy

### ISSUE THREAD

**Issue by tdphuochuy** [instagram4j/instagram4j#543]
My codes:
```
Authenticator proxyAuthenticator = new Authenticator() {
			  @Override public Request authenticate(Route route, Response response) throws IOException {
			       String credential = Credentials.basic("proxyusername", "proxypassword");
			       return response.request().newBuilder()
			           .header("Proxy-Authorization", credential)
			           .build();
			  }
			};
			Proxy proxy = new Proxy(Proxy.Type.HTTP,new InetSocketAddress("1.2.3.4", 1234));				
		OkHttpClient.Builder builder = new OkHttpClient.Builder();
		  builder.followRedirects(true);
		  OkHttpClient client = builder
				  .proxy(proxy)
				  .proxyAuthenticator(proxyAuthenticator)
				  .build();
		IGClient igclient = IGClient.builder()
		        .username("user")
		        .password("password")
		        .client(client)
		        .login();
		
		 FeedUserRequest req = new FeedUserRequest(7961647657L);
		 FeedUserResponse response = igclient.sendRequest(req).join();
         System.out.println((response.getItems().get(0).getId()));
```
Error:
```
Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: login_required
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:86)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:152)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:136)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException: login_required
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:149)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 7 more
```
Maven:
```
	<dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp</artifactId>
        <version>4.7.2</version>
    </dependency>
    <dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp-urlconnection</artifactId>
        <version>4.7.2</version>
    </dependency>
    <dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	<artifactId>jackson-databind</artifactId>
	<version>2.10.0.pr1</version>
    </dependency>
 <dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-annotations</artifactId>
  <version>2.12.0</version>
</dependency>
```
The codes above work fine without proxy or client but unable to login with proxy. I have tried different proxies as well.

**Comment by jvogit** [comment]
Sorry, it is a bit confusing, but when you make your custom http client you did not set a cookie jar. You will need to set a cookie jar such as javanetcookiejar. This is the reason for error on login since cookies are not being used.

Additionally you may initialize a new client from the default client:
```java
IGUtils.defaultHttoClientBuilder()
.proxy(...)
...
.build();
```
Which will set the cookie jar in the builder.
