### ISSUE TITLE
running Problem 

### ISSUE THREAD

**Issue by PejmanDaie** [instagram4j/instagram4j#559]
I checked all the libraries and conflicts but still when I call the login as it mention in documents it turn the following error 
I spend a long time to fix the error, still no hope . 
java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
	at okio.Segment.writeTo(Segment.kt:164) ~[okio-2.6.0.jar:?]
	at okio.Segment.compact(Segment.kt:147) ~[okio-2.6.0.jar:?]
	at okio.Buffer.write(Buffer.kt:1854) ~[okio-2.6.0.jar:?]
	at okio.Buffer.read(Buffer.kt:1865) ~[okio-2.6.0.jar:?]
	at okio.Buffer.writeAll(Buffer.kt:1655) ~[okio-2.6.0.jar:?]
	at okio.Options$Companion.buildTrieRecursive(Options.kt:187) ~[okio-2.6.0.jar:?]
	at okio.Options$Companion.buildTrieRecursive(Options.kt:174) ~[okio-2.6.0.jar:?]
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113) ~[okio-2.6.0.jar:?]
	at okio.Options$Companion.of(Options.kt:72) ~[okio-2.6.0.jar:?]
	at okhttp3.internal.Util.<clinit>(Util.kt:72) ~[okhttp-4.7.2.jar:?]
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309) ~[okhttp-4.7.2.jar:?]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41) ~[okhttp-4.7.2.jar:?]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47) ~[okhttp-4.7.2.jar:?]
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471) ~[okhttp-4.7.2.jar:?]
	at com.github.instagram4j.instagram4j.utils.IGUtils.defaultHttpClientBuilder(IGUtils.java:215) ~[instagram4j-2.0.3.jar:?]
	at com.github.instagram4j.instagram4j.IGClient$Builder.lambda$build$1(IGClient.java:234) ~[instagram4j-2.0.3.jar:?]
	at java.util.Optional.orElseGet(Unknown Source) ~[?:1.8.0_271]
	at com.github.instagram4j.instagram4j.IGClient$Builder.build(IGClient.java:234) ~[instagram4j-2.0.3.jar:?]
	at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:239) ~[instagram4j-2.0.3.jar:?]
	at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:248) ~[instagram4j-2.0.3.jar:?] 
	
	
	I use Maven , my java version is: 1.8.0_271

**Comment by jvogit** [comment]
> I checked all the libraries and conflicts but still when I call the login as it mention in documents it turn the following error
> I spend a long time to fix the error, still no hope .
> java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
> at okio.Segment.writeTo(Segment.kt:164) ~[okio-2.6.0.jar:?]
> at okio.Segment.compact(Segment.kt:147) ~[okio-2.6.0.jar:?]
> at okio.Buffer.write(Buffer.kt:1854) ~[okio-2.6.0.jar:?]
> at okio.Buffer.read(Buffer.kt:1865) ~[okio-2.6.0.jar:?]
> at okio.Buffer.writeAll(Buffer.kt:1655) ~[okio-2.6.0.jar:?]
> at okio.Options$Companion.buildTrieRecursive(Options.kt:187) ~[okio-2.6.0.jar:?]
> at okio.Options$Companion.buildTrieRecursive(Options.kt:174) ~[okio-2.6.0.jar:?]
> at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113) ~[okio-2.6.0.jar:?]
> at okio.Options$Companion.of(Options.kt:72) ~[okio-2.6.0.jar:?]
> at okhttp3.internal.Util.(Util.kt:72) ~[okhttp-4.7.2.jar:?]
> at okhttp3.internal.concurrent.TaskRunner.(TaskRunner.kt:309) ~[okhttp-4.7.2.jar:?]
> at okhttp3.ConnectionPool.(ConnectionPool.kt:41) ~[okhttp-4.7.2.jar:?]
> at okhttp3.ConnectionPool.(ConnectionPool.kt:47) ~[okhttp-4.7.2.jar:?]
> at okhttp3.OkHttpClient$Builder.(OkHttpClient.kt:471) ~[okhttp-4.7.2.jar:?]
> at com.github.instagram4j.instagram4j.utils.IGUtils.defaultHttpClientBuilder(IGUtils.java:215) ~[instagram4j-2.0.3.jar:?]
> at com.github.instagram4j.instagram4j.IGClient$Builder.lambda$build$1(IGClient.java:234) ~[instagram4j-2.0.3.jar:?]
> at java.util.Optional.orElseGet(Unknown Source) ~[?:1.8.0_271]
> at com.github.instagram4j.instagram4j.IGClient$Builder.build(IGClient.java:234) ~[instagram4j-2.0.3.jar:?]
> at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:239) ~[instagram4j-2.0.3.jar:?]
> at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:248) ~[instagram4j-2.0.3.jar:?]
> 
> ```
> I use Maven , my java version is: 1.8.0_271 
> ```

Sorry for delay. I hope your issue is fixed.

It appears okhttp3 is used but this library uses okhttp4.
