### ISSUE TITLE
Companion okhttp3 error

### ISSUE THREAD

**Issue by Spidersaw** [instagram4j/instagram4j#577]
Hello, I've imported instagram4j with maven 
<dependency>
  <groupId>com.github.instagram4j</groupId>
  <artifactId>instagram4j</artifactId>
  <version>2.0.4</version>
</dependency>

however when I try to login I get this error:

Exception in thread "main" java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:73)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at com.github.instagram4j.instagram4j.utils.IGUtils.defaultHttpClientBuilder(IGUtils.java:215)
	at com.github.instagram4j.instagram4j.IGClient$Builder.lambda$build$1(IGClient.java:234)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.github.instagram4j.instagram4j.IGClient$Builder.build(IGClient.java:234)
	at com.github.instagram4j.instagram4j.IGClient$Builder.login(IGClient.java:253)
	at jframehandler.InstagramConnector(jframehandler.java:637)
	at jframehandler.<init>(jframehandler.java:147)
	at MainActivity.main(MainActivity.java:23)

The code I'm using is that:

		igClient = IGClient.builder()
		        .username("usrn")
		        .password("pasw").login();

why do I get that error? I couldn't solve it in any way

**Comment by Spidersaw** [comment]
It was another version of okio conflicting with the project.
