### ISSUE TITLE
Send more than 2 photos to the album...

### ISSUE THREAD

**Issue by pbadun** [instagram4j/instagram4j#589]
I send an album, up to 10 photos. I get an error. Only 2 photos are sent :(

`Scanner scanner = new Scanner(System.in);
        Callable<String> inputCode = () -> {
            System.out.print("Please input code: ");
            return scanner.nextLine();
        };
        IGClient.Builder.LoginHandler challengeHandler = (client, response) -> {
            return IGChallengeUtils.resolveTwoFactor(client, response, inputCode);
        };
        IGClient client = IGClient.builder().
                username(name)
                .password(pass)
                .onChallenge(challengeHandler)
                .login();
        List<TimelineAction.SidecarInfo> info =
                Arrays.asList(
                        TimelineAction.SidecarPhoto.from(new File("ph_0.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_1.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_2.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_3.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_4.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_5.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_6.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_7.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_8.jpg")),
                        TimelineAction.SidecarPhoto.from(new File("ph_9.jpg"))
                );
        IGResponse response = client.actions().timeline()
                .uploadAlbum(
                        info,
                        "House")
                .join();
        log(response.getStatus());`

`Start
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error 2
Stop
java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:86)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:152)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:136)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:149)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 7 more`

**Comment by pbadun** [comment]
The problem is that not all photos are uploaded to the server:

[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1622469108997_0_5969244574 with body (truncated) : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed

OR

[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1622469405016_0_5645973491 : 400
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/rupload_igphoto/1622469405016_0_5645973491 with body (truncated) : {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed

How can I upload images separately, check for errors, and then publish the album to the feed?

**Comment by jvogit** [comment]
Make sure all images/videos are in proper format and ratio acceptable by Instagram

**Comment by NanoSpicer** [comment]
I am facing the same problem. For me the _second_ request always returns a 400.

I've written an algorithm that attempts to upload the album and if it fails then it attempts the single photo upload. 

- Album upload always fails (usually second request returns a 400)
- Single upload always works

I am sure photos are in acceptable format for instagram since I use `imagemagick` to ensure all of them are 1080x1080 and use JPEG format for all of them (checked the resolution in a blog post about how to become an influencer 💩 )

**Comment by pbadun** [comment]
I got around the situation like this:

`private void uploadTest(String[] f, String caption) throws IGLoginException, IOException, IGResponseException, ClassNotFoundException, Exception {
        List<MediaConfigureSidecarRequest.SidecarChildrenMetadata> metadata = new ArrayList<>();

        for (String s : f) {
            File firstPhoto = new File(s);
            byte[] firstImgData = Files.readAllBytes(firstPhoto.toPath());
            // upload photo
            IGRequest<RuploadPhotoResponse> uploadFirstPhoto =
                    new RuploadPhotoRequest(
                            firstImgData,
                            "1",
                            String.valueOf(System.currentTimeMillis()),
                            true);
            RuploadPhotoResponse e = client.sendRequest(uploadFirstPhoto).join();
            if (e.getStatusCode() != 200) {
                //TODO phono NOT upload 
                continue;
            }
            Log.dt(e.toString());
            String firstId = e.getUpload_id();
            metadata.add(new MediaConfigureSidecarRequest.SidecarChildrenMetadata(firstId));
            Thread.sleep(7);
        }
        IGRequest<?> configReq = new MediaConfigureSidecarRequest(
                new MediaConfigureSidecarRequest
                        .MediaConfigureSidecarPayload()
                        .caption(caption)
                        .children_metadata(metadata));
        //.location(location));
        IGResponse response = client.sendRequest(configReq).join();
        Log.dt(response.getStatus());
    }
`

**Comment by NanoSpicer** [comment]
I'll certainly give this a try this afternoon; thanks!

**Comment by NanoSpicer** [comment]
@pbadun Just tried and it worked flawlessly! Thanks for the solution!
