### ISSUE TITLE
Bug on login

### ISSUE THREAD

**Issue by Ziedelth** [instagram4j/instagram4j#606]
Hi,
I just installed the package with Maven (version 2.0.5), and when I try to log in with my credentials, I have this that appears and persists...
For the code, I just copy / paste the example code of connection.
Is there a solution?

Thanks for your future answer.

`[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://b.i.instagram.com/api/v1/launcher/sync/
Exception in thread "main" java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at com.github.instagram4j.instagram4j.requests.IGPostRequest.getRequestBody(IGPostRequest.java:41)
	at com.github.instagram4j.instagram4j.requests.IGPostRequest.formRequest(IGPostRequest.java:27)
	at com.github.instagram4j.instagram4j.IGClient.sendRequest(IGClient.java:127)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.github.instagram4j.instagram4j.actions.async.AsyncAction.executeRequestsAsync(AsyncAction.java:30)
	at com.github.instagram4j.instagram4j.actions.simulate.SimulateAction.preLoginFlow(SimulateAction.java:64)
	at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:250)
	at com.github.instagram4j.instagram4j.IGClient$Builder.simulatedLogin(IGClient.java:258)
	at TestInstagram.main(TestInstagram.kt:11)`

**Comment by nickbarban** [comment]
I've got same problem too. Is there any solution?

**Comment by nickbarban** [comment]
solved by using
	```
<dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp</artifactId>
        <version>4.7.2</version>
    </dependency>

    <dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp-urlconnection</artifactId>
        <version>4.7.2</version>
    </dependency>
```

**Comment by Ziedelth** [comment]
> solved by using
> 
> ```
> 	<dependency>
>         <groupId>com.squareup.okhttp3</groupId>
>         <artifactId>okhttp</artifactId>
>         <version>4.7.2</version>
>     </dependency>
> 
>     <dependency>
>         <groupId>com.squareup.okhttp3</groupId>
>         <artifactId>okhttp-urlconnection</artifactId>
>         <version>4.7.2</version>
>     </dependency>
> ```

Ok, problem solved with dependencies, I also had an incompatibility with Selenium which is solved
