### ISSUE TITLE
Library not woring with AbilityBot

### ISSUE THREAD

**Issue by FabioGrossi** [instagram4j/instagram4j#617]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Describe the bug

The library alone works completely. The problem occurs when I insert a tall library in the pom (https://github.com/rubenlagus/TelegramBots/tree/master/telegrambots-abilities)
`
<dependency>
            <groupId>org.telegram</groupId>
            <artifactId>telegrambots-abilities</artifactId>
            <version>5.3.0</version>
        </dependency>
`

Running the code after inserting the new library I get this error:
`
Exception in thread "main" java.lang.NoSuchMethodError: 'byte[] kotlin.collections.ArraysKt.copyInto(byte[], byte[], int, int, int)'
	at okio.Segment.writeTo(Segment.kt:164)
	at okio.Segment.compact(Segment.kt:147)
	at okio.Buffer.write(Buffer.kt:1854)
	at okio.Buffer.read(Buffer.kt:1865)
	at okio.Buffer.writeAll(Buffer.kt:1655)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:187)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:174)
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:113)
	at okio.Options$Companion.of(Options.kt:72)
	at okhttp3.internal.Util.<clinit>(Util.kt:72)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at com.github.instagram4j.instagram4j.utils.IGUtils.defaultHttpClientBuilder(IGUtils.java:217)
	at com.github.instagram4j.instagram4j.IGClient.deserialize(IGClient.java:201)
	at com.fabiogrossi.spottedinstagrampagemanager.instagram.InstagramUserManager.getClientFromDeserialization(InstagramUserManager.java:70)
	at com.fabiogrossi.spottedinstagrampagemanager.instagram.InstagramUserManager.login(InstagramUserManager.java:57)
	at com.fabiogrossi.spottedinstagrampagemanager.PageManager.main(PageManager.java:44)
`

### How to reproduce

1. Specify steps to reproduce

Insert instagram4j, TelegramBotsAPI and TelegramBotsAPI-AbilityBot module in pom.xml and try logging into instagram acount with IGClient#builder

**Comment by jvogit** [comment]
It looks like your build dependencies have Okhttp 3, but the library uses Okhttp 4

**Comment by FabioGrossi** [comment]
Any way to solve?
