### ISSUE TITLE
FriendshipsFeeds - unable to fetch followers

### ISSUE THREAD

**Issue by sanchezik** [instagram4j/instagram4j#631]
I faced with a problem in getting Followers (btw getting Followings is OK).

Here is my code:
`FeedUsersResponse response =
                    new FriendshipsFeedsRequest(9999999999L, FriendshipsFeedsRequest.FriendshipsFeeds.FOLLOWERS, "0")
.execute(client).join();`

It always throws this Exception:

> java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: unable to fetch followers

StackTrace looks like that:

> Exception in thread "Timer-0" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: unable to fetch followers
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:86)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:152)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:136)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException: unable to fetch followers
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:149)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 7 more

The same code works fine when I'm getting my own followings, using _FriendshipsFeedsRequest.FriendshipsFeeds.**FOLLOWING**_ enumeration.

Also I've found that in library's tests in file _friendships/FriendshipsTest.java_ -> method _testFollowers()_ -> there are double testing of Follow**ings**. I suppose there should be Followers+Followings. Maybe the reason of that is the same as mine: it's just not worked properly for Follow**ers** :(

**Comment by yorkeJohn** [comment]
I am experiencing the same issue.

**Comment by sanchezik** [comment]
Meanwhile I noticed this Instagram's logic:
- (exceptional case) for getting followers: URL = _/api/v1/friendships/999999999/followers/?count=12&max_id=QVFBSm1OVnM5TXBzL<... long string here ....>Q0hMaA%3D%3D&search_surface=follow_list_page_
- (worked fine case) for getting followings: URL = _/api/v1/friendships/999999999/following/?count=12&max_id=24_

I've tried to make a wrapper for FriendshipsFeedsRequest, where there is an additional path param _search_surface_, but it didn't help. So the last difference betwen requests, which can cause an exception, is that encrypted **_max_id_** param. Maybe it will help somehow somebody in solving the issue...

**Comment by sanchezik** [comment]
**I found the solution:**

- while making the first request **don't** use _FriendshipsFeedsRequest_ constructor with 3 params, use that one without _max_id_ field instead. Example:
`FeedUsersResponse response = new FriendshipsFeedsRequest(9999999999L, FriendshipsFeedsRequest.FriendshipsFeeds.FOLLOWERS).execute(client).join();`

- after getting first "page" of followers, you can find correct _next_max_id_ field in the response (_FeedUsersResponse.java_). Just remember this value and iterate next requests using it. Example:
`FeedUsersResponse response = new FriendshipsFeedsRequest(9999999999L, FriendshipsFeedsRequest.FriendshipsFeeds.FOLLOWERS, "MYLONGSTRINGFROMNEXTMAXIDPARAM").execute(client).join();`

- when all followers are downloaded, _Next_max_id_ param will be _Null_. So you can use this condition for defining the last request.
