### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;

### ISSUE THREAD

**Issue by hims1008** [instagram4j/instagram4j#632]
i try this dependency for get feed data of Instagram but error occur in login method 
and error is 
      
      com.github.instagram4j.instagram4j.exceptions.IGLoginException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at com.github.instagram4j.instagram4j.IGClient$Builder.performLogin(IGClient.java:278)
        at com.github.instagram4j.instagram4j.IGClient$Builder.login(IGClient.java:255)

**Comment by ErrorxCode** [comment]
Actually, `java.lang.Base64` class is **not available on some android** emulators. For that, we have to use the `android.utils.Base64` class. But there's a catch, If developers use `android.utils.Base64` then the same error will occur in **Non-Android projects**

**Comment by lyg73** [comment]
Can you use org.apache.commons.codec.binary.Base64 or other base64 package for Base64 functions instad of java.lang.Base64?
