### ISSUE TITLE
findbyusername Throws massive exception

### ISSUE THREAD

**Issue by RaitonGG** [instagram4j/instagram4j#643]
### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Describe the bug

Sometimes when doing `client.actions().users().findByUsername(name).join()` I get an exception for no apparent reason. I can't find a way to fix this

### How to reproduce

1. Specify steps to reproduce
I just have a loop getting users by username
```java
UserAction userToFollow = client.actions().users().findByUsername(name).join();
```

### Expected behavior

expecting the user to be fetched

### Actual behavior

I just get this exception:

```java
java.util.concurrent.CompletionException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head>
<title>5xx Server Error</title>
</head>

<body>
<h1>5xx Server Error</h1>
</body>

</html>
"; line: 1, column: 2]
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:88)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:154)
	at java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:138)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html>
<head>
<title>5xx Server Error</title>
</head>

<body>
<h1>5xx Server Error</h1>
</body>

</html>
"; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1941)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:776)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4620)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4469)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at com.github.instagram4j.instagram4j.utils.IGUtils.jsonToObject(IGUtils.java:230)
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:84)
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:79)
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:69)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:151)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	... 7 more```

**Comment by jvogit** [comment]
It's responding with Internal Server Error from instagram's side. How do you use this request? Do you notice any patterns on what usernames it fails on?

**Comment by RaitonGG** [comment]
Not really, sometimes the same username will work and other times throw this error.
is the json parse fail on instagram's side? kind of weird for them to send us that @jvogit
