### ISSUE TITLE
It gives an error when trying to get the ones I follow.

### ISSUE THREAD

**Issue by sqayner** [instagram4j/instagram4j#649]
```java
Observable.fromCallable(new Callable<List<Profile>>() {
                            @Override
                            public List<Profile> call() throws Exception {
                                return App.client
                                        .actions()
                                        .users()
                                        .findByUsername("testaccount")
                                        .thenApply(userAction -> userAction.followingFeed().stream().flatMap(feedUsersResponse -> feedUsersResponse.getUsers().stream()).collect(Collectors.toList()))
                                        .join();
                            }
                        })
                        .subscribeOn(Schedulers.newThread())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(new Observer<List<Profile>>() {
                            @Override
                            public void onSubscribe(@NonNull Disposable d) {

                            }

                            @Override
                            public void onNext(@NonNull List<Profile> profiles) {
                                Toast.makeText(MainActivity.this, "followingcount: " + profiles.size(), Toast.LENGTH_SHORT).show();
                            }

                            @Override
                            public void onError(@NonNull Throwable e) {
                                e.printStackTrace();
                            }

                            @Override
                            public void onComplete() {

                            }
                        });
```

The follower version of this code works fine but this gives error.

## error:
```
java.util.concurrent.CompletionException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
     at [Source: (StringReader); line: 1, column: 2]
        at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:88)
        at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5$com-github-instagram4j-instagram4j-IGClient(IGClient.java:157)
        at com.github.instagram4j.instagram4j.IGClient$$ExternalSyntheticLambda6.apply(Unknown Source:6)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:882)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:864)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:484)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1990)
        at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:141)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
     at [Source: (StringReader); line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:632)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1941)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:776)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4620)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4469)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
        at com.github.instagram4j.instagram4j.utils.IGUtils.jsonToObject(IGUtils.java:230)
        at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:84)
        at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:79)
        at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:69)
        at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4$com-github-instagram4j-instagram4j-IGClient(IGClient.java:154)
        at com.github.instagram4j.instagram4j.IGClient$$ExternalSyntheticLambda7.apply(Unknown Source:6)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:612)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:587)
        	... 7 more
```

**Comment by ErrorxCode** [comment]
I suggest you to use [EasyInsta](https://github.com/ErrorxCode/EasyInsta)
library. It is too easy and also have fast developer support.

**Comment by sqayner** [comment]
When I changed the system language from Turkish to English, it started working properly.

**Comment by ErrorxCode** [comment]
I suggest you to use EasyInsta library instead. It has much simpler API and
also has good developer support.
Link : https://github.com/ErrorxCode/EasyInsta
