### ISSUE TITLE
NoClassDefFoundError - IGClient.builder() (since AS update)

### ISSUE THREAD

**Issue by xXSkyWalkerXx1** [instagram4j/instagram4j#685]
### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

After a long time I decided to create something with this IG-api. So, I updated Android-Studio and added the implementation of this api to my build.gradle. But, however, I get the following error, which I never had before:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sky.test, PID: 5352
    java.lang.NoClassDefFoundError: com.github.instagram4j.instagram4j.IGClient$Builder$$ExternalSyntheticLambda0
        at com.github.instagram4j.instagram4j.IGClient$Builder.<init>(IGClient.java:242)
        at com.github.instagram4j.instagram4j.IGClient.builder(IGClient.java:199)
```
So, does anyone know why or, better, how I can solve it? :D

[EDIT] I tried an old project and it worked.

**Comment by xXSkyWalkerXx1** [comment]
It has something to do with the device where I start the app.
At first I used "Galaxy Nexus Api 22" and after I used my own phone it worked.
