### ISSUE TITLE
Getting java.io.NotSerializableException: okhttp3.CookieJar$Companion$NoCookies while serializing Cookie

### ISSUE THREAD

**Issue by ashish-npnits** [instagram4j/instagram4j#696]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Describe the bug

Please provide a concise description of your bug and relevant code.

### How to reproduce

1. Specify steps to reproduce
```
IGClient lib = new IGClient.Builder().client(getProxyClient( host,  port)).username(username.strip()).password(password.strip())
					.onLogin((cli, lr) -> System.out.println(lr.getStatus())).login();
			
			File to = new File("src/main/resources/files/"+username+"_igclient.ser"),
					cookFile = new File("src/main/resources/files/"+username+"_cookie.ser");
			
			lib.serialize(to, cookFile);


public static OkHttpClient getProxyClient( String hostname, int port){
		
		Authenticator authenticator = null;
		
		
		if(hostname.contains("@")) {
			String[] hostnameSplit = hostname.split("@");
			String[] credentials = hostnameSplit[0].split(":");
			hostname = hostnameSplit[1];
			authenticator = new Authenticator() {
				  public Request authenticate(Route route, Response response) throws IOException {
				       String credential = Credentials.basic(credentials[0], credentials[1]);
				       return response.request().newBuilder()
				           .header("Proxy-Authorization", credential)
				           .build();
				  }
				};
		}
		Proxy proxy = new Proxy(Proxy.Type.HTTP,
		        new InetSocketAddress(hostname, port));
		CookieStore httpCookieStore = new BasicCookieStore();

		OkHttpClient client = null;
		if(authenticator !=null) {
			 client = new OkHttpClient.Builder()
					.connectTimeout(100, TimeUnit.SECONDS)
				    .writeTimeout(60, TimeUnit.SECONDS)
				    .readTimeout(60, TimeUnit.SECONDS)
				    .proxyAuthenticator(authenticator)
			        .proxy(proxy)
			        .build();
		}else {
			 client = new OkHttpClient.Builder()
					.connectTimeout(100, TimeUnit.SECONDS)
				    .writeTimeout(60, TimeUnit.SECONDS)
				    .readTimeout(60, TimeUnit.SECONDS)
				    
			        .proxy(proxy)
			        .build();
		}
		
		return client;
	}
```
### Expected behavior

The cookie should be saved in the file

### Actual behavior

java.io.NotSerializableException: okhttp3.CookieJar$Companion$NoCookies
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1193)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
	at com.github.instagram4j.instagram4j.utils.SerializeUtil.serialize(SerializeUtil.java:19)
	at com.github.instagram4j.instagram4j.IGClient.serialize(IGClient.java:221)
	at com.instagram.utils.IGLogin.<init>(IGLogin.java:61)
	at com.instagram.utils.IGLogin.getInstance(IGLogin.java:151)
	at com.instagram.controller.PostController.login(PostController.java:38)

**Comment by ashish-npnits** [comment]
public static OkHttpClient getProxyClient( String hostname, int port){
		
		Authenticator authenticator = null;
		
		
		if(hostname.contains("@")) {
			String[] hostnameSplit = hostname.split("@");
			String[] credentials = hostnameSplit[0].split(":");
			hostname = hostnameSplit[1];
			authenticator = new Authenticator() {
				  public Request authenticate(Route route, Response response) throws IOException {
				       String credential = Credentials.basic(credentials[0], credentials[1]);
				       return response.request().newBuilder()
				           .header("Proxy-Authorization", credential)
				           .build();
				  }
				};
		}
		Proxy proxy = new Proxy(Proxy.Type.HTTP,
		        new InetSocketAddress(hostname, port));

		OkHttpClient client = null;
		if(authenticator !=null) {
			 client = IGUtils.defaultHttpClientBuilder()
					.connectTimeout(100, TimeUnit.SECONDS)
				    .writeTimeout(60, TimeUnit.SECONDS)
				    .readTimeout(60, TimeUnit.SECONDS)
				    .proxyAuthenticator(authenticator)
			        .proxy(proxy)
			        .build();
		}else {
			 client = IGUtils.defaultHttpClientBuilder()
					.connectTimeout(100, TimeUnit.SECONDS)
				    .writeTimeout(60, TimeUnit.SECONDS)
				    .readTimeout(60, TimeUnit.SECONDS)
				    
			        .proxy(proxy)
			        .build();
		}
		
		return client;
	}
