### ISSUE TITLE
Login doesn't seem to work anymore

### ISSUE THREAD

**Issue by Athamax** [instagram4j/instagram4j#93]
Since this morning, the library can no longer log in:

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 6
0)): expected a valid value (number, String, array, object, 'true', 'false' or '
null')
 at [Source: <html>
<head>
<title>5xx Server Error</title>
</head>

<body>
<h1>5xx Server Error</h1>
</body>

</html>
; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimal
Base.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(Pars
erMinimalBase.java:456)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(Reader
BasedJsonParser.java:1906)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJ
sonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.jav
a:3834)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.ja
va:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842
)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRe
quest.java:139)
	at org.brunocvcunha.instagram4j.requests.InstagramRequest.parseJson(InstagramRe
quest.java:111)
	at org.brunocvcunha.instagram4j.requests.InstagramAutoCompleteUserListRequest.p
arseResult(InstagramAutoCompleteUserListRequest.java:43)
	at org.brunocvcunha.instagram4j.requests.InstagramAutoCompleteUserListRequest.p
arseResult(InstagramAutoCompleteUserListRequest.java:28)
	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramG
etRequest.java:56)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:202)
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:157)
```

Is there anything I can do to fix this?
The account is not the problem, worked fine for months, nothing changed.

**Comment by ChrisJSt** [comment]
I got the same issue when trying to log in.

**Comment by brunocvcunha** [comment]
Still having the problem? Working fine here.

**Comment by Athamax** [comment]
I still have the issue. To reproduce, you should be asked for a checkpoint (not 2FA, the "yeah it's me" confirmation in the app.) Happens if you log in from far away, aka try it on a server.
Up untill yesterday, when the check was asked you would just say "yes" in the app and it would work, and also remember from there onwards. Now they seem to have changed the http response, which is also resulting in some parsing error (at least that's what I can tell from the exception).

**Comment by charlieAndroidDev** [comment]
Take a look at this: https://github.com/mgp25/Instagram-API/issues/1741

This will effect this library ad well.  If you ever got a checkpoint in the past it means that you were flagged by Instagram as a potential spammer and if you can no longer log in from a server it most likely means you have been blocked in some way.
